services:
  frontend_poc:
    build: .
    environment:
      - PORT=8050
      - API_URL=http://backend:6942/
    ports:
      - 8050:8050
    restart: always
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
    external: true
